name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Use Java 12
      uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
    - uses: actions/checkout@v1
    - name: Production Build
      run: ./gradlew -Pprod -Pwar clean bootWar
      env:
        CI: true
    - name: Make .war file accessible
      run: ln -s `ls build/libs/` ./build/libs/Artemis.war
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: Artemis.war
        path: build/libs/Artemis.war
